CREATE TABLE author (
	author_id NUMBER(10),
	author_name VARCHAR2(100) NOT NULL, --NULL허용 안함
	author_desc VARCHAR2(500),
	PRIMARY KEY(author_id) --PK설정
);

SELECT * FROM AUTHOR;

CREATE TABLE book (
	book_id NUMBER(10),
	title VARCHAR2(100) NOT NULL,
	pubs VARCHAR2(100),
	pub_date DATE,
	author_id NUMBER(10),
	PRIMARY KEY(book_id),
	CONSTRAINT c_book_fk FOREIGN KEY (author_id)
	REFERENCES author(author_id) --REFERENCES를 안하면 관계가 없기때문에 ERD에서 따로따로 나온다.
);



INSERT INTO AUTHOR VALUES(1, '박경리', '토지작가');
INSERT INTO AUTHOR(AUTHOR_ID, AUTHOR_NAME) VALUES(2, '이문열');

SELECT * FROM AUTHOR a ;

UPDATE AUTHOR 
SET  AUTHOR_NAME = '강풀'
	,AUTHOR_DESC = '인기작가'
WHERE AUTHOR_ID = 1;

SELECT * FROM AUTHOR a 

DELETE FROM AUTHOR a 
WHERE AUTHOR_ID = 1;

SELECT * FROM AUTHOR a ;

DELETE FROM AUTHOR a 
WHERE AUTHOR_ID = 2;

ROLLBACK;

CREATE SEQUENCE SEQ_AUTHOR_ID
INCREMENT BY 1
START WITH 1;

INSERT INTO AUTHOR 
VALUES (SEQ_AUTHOR_ID.NEXTVAL, '이문열', '삼국지 작가');

DELETE FROM AUTHOR a ;

INSERT INTO AUTHOR VALUES(SEQ_AUTHOR_ID.NEXTVAL, '이문열', '경북양양');
INSERT INTO AUTHOR VALUES(SEQ_AUTHOR_ID.NEXTVAL, '박경리', '경상남도 통영');
INSERT INTO AUTHOR VALUES(SEQ_AUTHOR_ID.NEXTVAL, '유시민', '17대 국회의원');
INSERT INTO AUTHOR VALUES(SEQ_AUTHOR_ID.NEXTVAL, '기안84', '기안동에서 산 84년생');
INSERT INTO AUTHOR VALUES(SEQ_AUTHOR_ID.NEXTVAL, '강풀', '온라인 만화가 1세대');
INSERT INTO AUTHOR VALUES(SEQ_AUTHOR_ID.NEXTVAL, '김영하', '알쓸신잡');
COMMIT;

CREATE SEQUENCE SEQ_BOOK_ID
INCREMENT BY 1
START WITH 1;

SELECT * FROM BOOK;
SELECT * FROM AUTHOR a ;

INSERT INTO BOOK(BOOK_ID, TITLE, PUBS, PUB_DATE, AUTHOR_ID) VALUES(SEQ_BOOK_ID.NEXTVAL, '우리들의 일그러진 영웅', '다림', SYSDATE, 1);
INSERT INTO BOOK(BOOK_ID, TITLE, PUBS, PUB_DATE, AUTHOR_ID) VALUES(SEQ_BOOK_ID.NEXTVAL, '삼국지', '민음사', SYSDATE, 1);
INSERT INTO BOOK(BOOK_ID, TITLE, PUBS, PUB_DATE, AUTHOR_ID) VALUES(SEQ_BOOK_ID.NEXTVAL, '토지', '마로니에북스', SYSDATE, 2);
INSERT INTO BOOK(BOOK_ID, TITLE, PUBS, PUB_DATE, AUTHOR_ID) VALUES(SEQ_BOOK_ID.NEXTVAL, '유시민의 글쓰기 특강', '생각의길', SYSDATE, 3);
INSERT INTO BOOK(BOOK_ID, TITLE, PUBS, PUB_DATE, AUTHOR_ID) VALUES(SEQ_BOOK_ID.NEXTVAL, '패션왕', '중앙북스(books)', SYSDATE, 4);
INSERT INTO BOOK(BOOK_ID, TITLE, PUBS, PUB_DATE, AUTHOR_ID) VALUES(SEQ_BOOK_ID.NEXTVAL, '순정만화', '재미주의', SYSDATE, 5);
INSERT INTO BOOK(BOOK_ID, TITLE, PUBS, PUB_DATE, AUTHOR_ID) VALUES(SEQ_BOOK_ID.NEXTVAL, '오직두사람', '문학동네', SYSDATE, 6);
INSERT INTO BOOK(BOOK_ID, TITLE, PUBS, PUB_DATE, AUTHOR_ID) VALUES(SEQ_BOOK_ID.NEXTVAL, '26년', '재미주의', SYSDATE, 5);

COMMIT;

DELETE FROM BOOK b 
WHERE AUTHOR_ID = 4;

DELETE FROM AUTHOR a 
WHERE AUTHOR_ID = 4;

UPDATE BOOK 
SET PUB_DATE = '2012-02-04'
WHERE BOOK_ID  = 8;


SELECT b.BOOK_ID , b.TITLE , b.PUBS ,TO_CHAR(b.PUB_DATE ,'yyyy-mm-dd') pub_date,a.AUTHOR_ID ,a.AUTHOR_NAME ,a.AUTHOR_DESC 
FROM BOOK b , AUTHOR a 
WHERE b.AUTHOR_ID  = a.AUTHOR_ID;
